apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: "project1"
  JWT_SECRET: "supersecretkey123"
  MONGO_URI: "mongodb://mongodb:27017"
  MONGO_DB: "analytics_db"
  ANALYTICS_COLLECTION: "analytics"
